### ISSUE TITLE
Install command not working

### ISSUE THREAD

**Issue by EternallLight** [umbopepato/velociraptor#18]
Hello,

First of all, @umbopepato thanks for the work you're doing!
 
I'm taking my first look at Deno and came here from the 1st Deno mailing list issue. After running the install command `deno install --allow-read --allow-env --allow-run -n vr https://deno.land/x/velociraptor/cli.ts` from the documentation, I'm getting 404 error

```
error: Uncaught Error: Import 'https://deno.land/std@v1.0.0-rc1/fs/read_file_str.ts' failed: 404 Not Found
```

deno --version
```
deno 1.0.0-rc2
v8 8.4.300
typescript 3.8.
```

Please, take a look

**Comment by umbopepato** [comment]
Hi @EternallLight and thanks for reporting this.
I was aware of this problem and I was pretty convinced there was something going on with the deno website since those `std/...` versioned urls stopped working all of a sudden, despite being still visible on the browser (as you can see by visiting https://deno.land/std@v1.0.0-rc1/fs/read_file_str.ts). I just realized though that the versioning of the `std` library has somehow "diverged" from the main one and those urls won't be available anymore, neither in the web interface.
Should be working fine in `1.0.0-beta.3`

**Comment by EternallLight** [comment]
Yep, I also noticed that it is available in the browser.
Thanks for fixing this!
