### ISSUE TITLE
Add support for managing dependencies in deps.ts

### ISSUE THREAD

**Issue by trivikr** [umbopepato/velociraptor#25]
**Is your feature request related to a problem? Please describe.**
npm cli provides a way to manage dependencies using npm install.
* For example: `npm install express`

This command either adds a dependency or devDependency in package.json ([documentation](https://docs.npmjs.com/cli/install))

Although velociraptor is just advertised as a script runner for deno, it would be more useful if it can mange dependencies too (in `deps.ts`)

**Describe the solution you'd like**
velociraptor cli has an equivalent cli for add dependency.
* For example, `vr add https://deno.land/x/oak/mod.ts`

The above command could populate dependency in `deps.ts`
```ts
export * as oak from "https://deno.land/x/oak/mod.ts";
```

**Describe alternatives you've considered**
Manually managing dependencies in `deps.ts`

**Comment by trivikr** [comment]
The `add` command could be used to add specific versions as well.
* For example `vr add https://deno.land/x/oak@v3.7.0/mod.ts`

This would add `oak@3.7.0`
```ts
export * as oak from "https://deno.land/x/oak@v3.7.0/mod.ts";
```

In future, an `update` command could also be added for example:
* `vr update oak`

Assuming latest version is `oak@3.7.0`, the dependency would be updated to:
```ts
export * as oak from "https://deno.land/x/oak@v4.0.0/mod.ts";
```

**Comment by umbopepato** [comment]
Hi @trivikr, thanks for the proposal!

Dependency/package management is a much debated aspect about deno. There's a lot of discussion going on (see for example https://github.com/denoland/deno/issues/47, [Deno may need a module.json](https://dev.to/searchableguy/why-deno-may-need-a-module-json-dp4)), and some userland solutions are already starting to emerge, like [module.land](https://module.land) and [udd](https://github.com/hayd/deno-udd/tree/master).

With this said, I think such a dependency management layer on top of TS imports has some non-trivial implications, for instance:

- when I `vr add` a dependency, what members are re-exported? In your example you use a namespace export, but how do you choose how to name the namespaces and make sure to avoid collisions? Also, some users would probably find unacceptable having to use namespaces instead of named imports. On the other hand re-exporting everything from the module (`export * from ...`) loses the default export and raises the risk of name collision.
- What if the user doesn't use/doesn't want to use the `deps.ts/dev_deps.ts` pattern?

Probably [import maps](https://deno.land/manual/linking_to_external_code/import_maps) - that `module.land` uses - are more suitable for this, although they're currently marked as unstable and are not 100% guaranteed to remain.

As for the `update` functionality, `udd` essentially already does this pretty well.

What do you think?
